# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FitnessLogger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'
  pod 'CodableFirebase'
  pod 'SwiftMonkeyPaws', '~> 2.1.0'

  # Pods for FitnessLogger

  target 'FitnessLoggerTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftMonkey', :git => 'https://github.com/zalando/SwiftMonkey.git'
  end

  target 'FitnessLoggerUITests' do
    # Pods for testing
    pod 'SwiftMonkey', :git => 'https://github.com/zalando/SwiftMonkey.git'
  end

end
